### ISSUE TITLE
Expose a safe way to efficiently write to an uninitialized, fixed buffer

### ISSUE THREAD

**Issue by Marwes** [dtolnay/itoa#19]
Currently if I need to write an integer to a fixed size buffer I need to lookup how large of a buffer I need for the integer size and create it manually, either with zero initialization or unsafe. Further this buffer will not be directly written to as the crate creates its own buffer.

If the crate exposed a buffer type like https://docs.rs/ryu/0.2.6/ryu/struct.Buffer.html this could be avoided and hidden behind a safe interface.

```rust
pub trait Integer {
    const MAX_SIZE: usize;
}
pub struct Buffer<I> where I: Integer { buf : [u8: I::MAX_SIZE] }
```

Since associated constants are a relatively new Rust feature this could need some build.rs trickery and/or an extension trait but I'd be willing to submit a PR if this seems reasonable.

**Comment by dtolnay** [comment]
I like the API in ryu a lot. I would be on board with picking that up here. Please send a PR!

In your use case is it important to use the smallest possible buffer for each integer type or can we just use `[u8; 40]` everywhere which fits any primitive integer?

**Comment by Marwes** [comment]
I wouldn't say it is important (bench first and all) but my first thought was just to expose the max size. Other than that it would make it possible to preserve the current internal api which has the explicit per integer sizes so I figured why not do that tiny bit of optimization.

**Comment by dtolnay** [comment]
I would go with `[u8; 40]` for now even if it means some restructuring internally. If you decide to implement both ways and find measurably better performance from using a smaller buffer for smaller types, then we can go with the faster way.
