### ISSUE TITLE
128 max lengths

### ISSUE THREAD

**Issue by gilescope** [dtolnay/itoa#29]
Hi was just passing through and might have spotted something slightly amiss.

I agree that i64 and u64 has different max lengths (19, 20) but I don't believe this is the case for 128:

https://github.com/dtolnay/itoa/blob/ac8183cdafe59ac25635ea3f4320cd2d34022f7f/src/lib.rs#L354

Shouldn't they both be 39?

(also if we're there we should probably make that other constant only available with the feature)

(If you agree I'll raise a PR to adjust.)

**Comment by dtolnay** [comment]
`println!("{}", i128::MIN.to_string().len());`

**Comment by gilescope** [comment]
Ah I'm missing the minus sign. Makes sense now. Sorry!
