### ISSUE TITLE
Thoughts on adding a MAX_STR_LEN param to the Integer trait?

### ISSUE THREAD

**Issue by SUPERCILEX** [dtolnay/itoa#44]
https://github.com/bytecodealliance/rustix/pull/1201/files#diff-0c1bf5756f1b043ec04ef125becca3922c5dd96e503c83dc1584649167f04d00R55

Over in rustix we're trying to move some buffers to maybe uninit. Unfortunately, knowing how big a buffer will be results in really ugly code (see link above), so I'd like to propose two changes to make unsafe code easier to write with itoa:
- Add a MAX_STR_LEN constant so that consumers can target specific integers and size their buffers appropriately. Independently of rustix, this would be quite useful for sizing itoa derived buffers as I've realized I frequently hardcode these numbers. Example: https://github.com/SUPERCILEX/ftzz/blob/7ed248fa45813e148ff4eb35d7e497e1d5a5d2fe/src/utils/file_names.rs#L57
- Add an unsafe hint to tell the compiler how much of itoa's buffer is used (based on MAX_STR_LEN). This will enable optimizations when copying from itoa's buffer to our own.

cc @sunfishcode

**Comment by dtolnay** [comment]
Yes, I would welcome a PR for this.
